<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [1]:
#Task 1 
a = "PYTHON"
d_eq = []
ch = []
for i in a :
    num=ord(i)      # logic to convert all char to decimal
    d_eq.append(num)
print(d_eq)
for i in d_eq :
    char=chr(i)     # logic to convert back decimal to char
    ch.append(char)
print(ch)

[80, 89, 84, 72, 79, 78]
['P', 'Y', 'T', 'H', 'O', 'N']


### Task2
- Raise 2 to the power 10

In [2]:
# Task 2 
a = 2**10   # logic for power of 2
print(a)

1024


### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [4]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]

In [5]:
for i in range(1, len(list1), 2):   # printing alternate elements starting from Japan
    print(list1[i])

Japan
China
Africa
France
Germany


In [6]:
indexes = [1, 4, 5, 8]
for index in indexes:         # printing elements at indexes 1,4,5,8
    print(list1[index])

Japan
Australia
Africa
Italy


### Task4

- From the given list, extract the "Hex" and print it

In [7]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]

In [8]:
hex_element = list2[2][2][2][0]        # printing "Hex"
print(hex_element)

Hex


### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [9]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}

In [10]:
topd_keyword = dict1["Tevatron"][3]["Projects"][1]           # printing the keyword "TOPD"
print(topd_keyword)

TOPD


### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [12]:
# Task 6
height = int(input()) 
def height_category(height):     # logic for checking height categories
    if height <= 167:
        return "Short"
    elif 168 <= height < 182:
        return "Average"
    else:
        return "Tall"
category = height_category(height)
print(category)

182
Tall


### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [13]:
# Task 7
uppercase_alphabets = [chr(i) for i in range(65, 91)]   # generating uppercase alphabets
print(' '.join(uppercase_alphabets))

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z


### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [ ]:
# Task 8
import numpy as np

integers_array = np.arange(100, 201)    # generating integers between 100 and 200
print(integers_array)


### Task9

Print all even integers from the array created in Task8

In [ ]:
# Task 9
even_integers = integers_array[integers_array % 2 == 0]   # logic for printing all even integers
print(even_integers)

### Task10

Print all 100 values from Standard Normal Distribution

In [ ]:
# Task 10
import numpy as np

standard_normal_values = np.random.randn(100)     # printing 100 values from standard normal distribution
print(standard_normal_values)


### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [14]:
# Task 11
import numpy as np

random_array = np.random.rand(4)    # numpy array of random number
print(random_array)


[0.33802489 0.07184528 0.33749382 0.32124647]


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [15]:
# Task 12
import numpy as np

evenly_spaced_array = np.linspace(10, 20, 100)    # array of 100 values evenly spaced between 10 and 20
print(evenly_spaced_array)


[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [20]:
# Task 13
import numpy as np

# Create a 5x5 NumPy array
array_5x5 = np.random.random((5, 5))

# Print the last 3 rows
last_3_rows = array_5x5[2:]
print(last_3_rows)


[[0.20685573 0.91254645 0.57655418 0.45236246 0.17417681]
 [0.76110582 0.21978499 0.10697084 0.27984347 0.3333398 ]
 [0.61278982 0.03697133 0.10777095 0.77007915 0.40733115]]


### Task14

Using the array created above in Task13, Print the first 2 columns

In [21]:
# Task 14
# Print the first 2 columns
first_2_columns = array_5x5[:, :2]
print(first_2_columns)

[[0.91849351 0.8458942 ]
 [0.38142791 0.98554776]
 [0.20685573 0.91254645]
 [0.76110582 0.21978499]
 [0.61278982 0.03697133]]


### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [22]:
# Task 15
import numpy as np

# Create an array of 25 random values
random_array = np.random.random(25)

# Find the sum of all elements
sum_of_elements = np.sum(random_array)
print("Sum of all elements:", sum_of_elements)

# Find the element with maximum value
max_element = np.max(random_array)
print("Maximum value:", max_element)

# Find the element with minimum value
min_element = np.min(random_array)
print("Minimum value:", min_element)


Sum of all elements: 10.622516967528641
Maximum value: 0.95605921899439
Minimum value: 0.027997269463401198


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [23]:
# Task 16

# Create an array of 25 random values
random_array = np.random.random((5, 5))

# List of column indexes to print
column_indexes = [1, 3, 4]

# Print columns with specified indexes
selected_columns = random_array[:, column_indexes]
print(selected_columns)

[[0.62220336 0.59837863 0.53882024]
 [0.02177686 0.79016735 0.38908352]
 [0.2665241  0.21909091 0.93552868]
 [0.21205399 0.66162957 0.42281947]
 [0.34436065 0.26084277 0.29949648]]


### Task17
Read car_sales.csv

In [24]:
# Task 17
import pandas as pd

# Load the CSV file into a DataFrame
car_sales_df = pd.read_csv('car_sales.csv')

### Task18
Sort data frame in ascending order of the Price column

In [4]:
# Task 18: Sort data frame in ascending order of the Price column
sorted_by_price = car_sales_df.sort_values(by='Price', ascending=True)
print("Task 18 - Sorted by Price:")
print(sorted_by_price)

Task 18 - Sorted by Price:
    Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   



### Task19
Print number of unique car manufacturers in the data

In [5]:
# Task 19: Print number of unique car manufacturers in the data
unique_manufacturers = car_sales_df['Manufacturer'].nunique()
print("Task 19 - Number of unique car manufacturers:", unique_manufacturers)

Task 19 - Number of unique car manufacturers: 32


### Task20
Print the maximum Wheelbase from the data

In [6]:
# Task 20: Print the maximum Wheelbase from the data
max_wheelbase = car_sales_df['Wheelbase'].max()
print("Task 20 - Maximum Wheelbase:", max_wheelbase)

Task 20 - Maximum Wheelbase: 119


### Task21
Print the car Model which has maximum Wheelbase

In [7]:
# Task 21: Print the car Model which has maximum Wheelbase
max_wheelbase_model = car_sales_df.loc[car_sales_df['Wheelbase'].idxmax(), 'Model']
print("Task 21 - Car Model with maximum Wheelbase:", max_wheelbase_model)

Task 21 - Car Model with maximum Wheelbase: Aerostar


### Task22

Print the Details of car with maximum passenger capacity

In [10]:
# Task 22: Print the Details of car with maximum passenger capacity
max_passenger_capacity_car = car_sales_df.loc[car_sales_df['Passengers'].idxmax()]
print("Task 22 - Details of car with maximum passenger capacity:")
print(max_passenger_capacity_car)

Task 22 - Details of car with maximum passenger capacity:
Unnamed: 0                         17
Manufacturer                Chevrolet
Model                           Astro
Type                              Van
Min.Price                        14.7
Price                            16.6
Max.Price                        18.6
MPG.city                           15
MPG.highway                        20
AirBags                          None
DriveTrain                        4WD
Cylinders                           6
EngineSize                        4.3
Horsepower                        165
RPM                              4000
Rev.per.mile                     1790
Man.trans.avail                    No
Fuel.tank.capacity               27.0
Passengers                          8
Length                            194
Wheelbase                         111
Width                              78
Turn.circle                        42
Rear.seat.room                   33.5
Luggage.room                  